name: supabase_flutter
description: Flutter integration for Supabase. This package makes it simple for developers to build secure and scalable products.
version: 2.8.0
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/supabase_flutter'
documentation: 'https://supabase.com/docs/reference/dart/introduction'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  app_links: '>=3.5.0 <7.0.0'
  async: ^2.12.0
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  http: '>=0.13.4 <2.0.0'
  meta: ^1.16.0
  supabase: 2.5.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  logging: ^1.3.0

dev_dependencies:
  dart_jsonwebtoken: ^2.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  path: ^1.9.1

platforms:
  android:
  ios:
  macos:
  web:
  windows:

flutter:
  uses-material-design: true